version: '3.9'

services:
  web:
    build: .  
    # หรือ image: php:8.2-apache  ถ้าไม่ custom
    container_name: crm-web  #
    ports:
      - "8800:80"  
    volumes:
      - ${Path}
    depends_on:
      - db
    networks:
      - crm-net 
    restart: always

  db:
    image: mysql:5.7
    container_name: crm-db  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: crm  
    ports:
      - "3307:3306"  # ใช้เดิมได้
    volumes:
      - crm_data:/var/lib/mysql  
      - ./crm.sql:/docker-entrypoint-initdb.d/crm.sql  
    networks:
      - crm-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm-phpmyadmin  
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${PMA_PASSWORD}  
    ports:
      - "8801:80"  
    depends_on:
      - db
    networks:
      - crm-net

networks:
  crm-net:

volumes:
  crm_data:  
